### ISSUE TITLE
"neg=keep IVL" and "Shortcut"

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/ReMemorize#1]
Congratulations to this addon.
I have two questions:

1) I do not understand what the addon does when inserting a negative number:

![image](https://user-images.githubusercontent.com/42243532/48259479-3464ff80-e3ff-11e8-9ef3-1d5928522016.png)

2) Is it possible to insert a shortcut to this option?

![image](https://user-images.githubusercontent.com/42243532/48259573-8c036b00-e3ff-11e8-890f-dcd0cd791f97.png)

**Comment by lovac42** [comment]
0 = make card new, you don't need a short cut as you won't be using this often. Leave the shortcut for other addons.
Positive number to change the due date and interval.
Negative number to change the due date only keeping the current interval the same.

edit: To elaborate, say you have a matured card with an ivl of 100 due today. -7 would shift the due date by 1 week keeping the ivl to 100. +7 would change the due date to 7 and the ivl to 7 making this a young card.

**Comment by cjdduarte** [comment]
Thank you
