### ISSUE TITLE
allow search for rescheduled cards in the browser

### ISSUE THREAD

**Issue by ijgnd** [lovac42/ReMemorize#11]
`rated:1:0` doesn't work. At the moment I use `rated:1 -rated:1:1 -rated:1:2 -rated:1:3 -rated:1:4` which is quite long. Maybe it would make sense to offer this search option? The relevant function is [_findRated from anki/find.py](https://github.com/dae/anki/blob/master/anki/find.py#L296).

Background: I frequently reschedule cards. Quite often it's cards that I want to relearn later (when hopefully I know more about this topic so that it's easier). I could suspend but then I would have to unsuspend. When rescheduling I'm always afraid to accidently reschedule too far into the future, e.g. I might have typed in 111 instead of 11. The most elegant way to quickly rule out such mistakes should be to search for something like `rated:100:0` (if 100 were allowed). 

If you like this idea and decide to modify _findRated maybe you could slightly increase the current 31day limit to maybe 100? This limit is more than 6 years old and today's slowest machines should be considerably quicker. Also I assume that people who install add-ons are usually more interested in computers than average and this interest usually corresponds with slightly stronger machines.

P.S. If you wonder about why I would post this issue. I finally reduced my "Extended quick reschedule in reviewer" to a fancy touch-friendly skin for ReMemorize that calls your hooks. My previous solution to catch too long intervals was overly complicated and error-prone compared to a simple search. Also: If you are interested in an alternative gui I would love to see all the things a professional would fix in my code. Then I could delete my add-on.

thanks for your time and this essential add-on.

**Comment by lovac42** [comment]
I will look into the search thing, thanks for the idea. Usually I avoid front end stuff, so a gui isn't going to happen. Glad you are maintaining one so I don't have to.

**Comment by lovac42** [comment]
I think I will separate this as an extension to prevent conflicts with other addons and make it available once the new addon manager is ready. That will prevent ReMemorize from causing conflicts for non-essential functions.

https://github.com/lovac42/ReMemorize/releases/tag/v0.0.2

**Comment by ijgnd** [comment]
Thank you very much for fixing this problem for me.
