### ISSUE TITLE
reschedule in browser without changing interval

### ISSUE THREAD

**Issue by omega3** [lovac42/ReMemorize#14]
Hello

Is it possible to add option to choose several cards in a browser and reschedule without changing interval? Preferably with from given number of days to given number of days (as in default reschedule option). 

And preferably, regardless of what state they are: new, learning, review, due, whatever.

Default reschedule option changes interval. 

In Browser I don't see "Study" menu.

This may seem a bit strange idea concerning new cards, but I have over 80 new cards with the same headword and I don't wont them to enter my learning process day after day. If I had a 1000 of new cards perhaps it would be enough to use reposition option but with like a 100 new it gives nothing. And rescheduling changes interval, so they are treated by Anki as not new.

**Comment by lovac42** [comment]
Please read the readme before filing a bug report.
This is also written in the wiki.
https://github.com/lovac42/ReMemorize/wiki/ReMemorize-User-Inputs

**Comment by omega3** [comment]
It is not a bug report. It is feature request.

I read:
From main page:

> Positive integer to reschedule the card's ivl and due date.
> Negative integer to reschedule the due date only. Keeping the current IVL.

In the wiki:

> In The Browser:
> reschedule dialog: (positive integer) new interval and due date (from today)
> reposition: (positive integer) due date only (from today)

This I understand as: in reschedule dialog only positive integer is possible, which means both new interval and due date will be changed.

I checked this and indeed it works like this. No negative integer is possible in reschedule dialog.

So, my request is about being able to use negative integer in reschedule dialog in the Browser (to be able to change due date only).

Normally, when I set that I want 10 new cards a day I need to learn them one day after another. 80 new cards equals 8 days, one after the other. Every day I get new cards to learn. Repositioning them doesn't change it, when I don't have enough new cards. 

If it was possible to change due day of new cards in browser they will enter learning process at a given time that I would set in reschedule dialog. For example I have 80 new cards with the same headword. I want to spread them across several months. This way I imagine I could have five new cards today, zero new cards (with this particular headword) tomorrow. And the day after tomorrow again five new cards with this headword.

**Comment by lovac42** [comment]
Negative numbers aren't allowed in those dialogs, so it was split into reschedule and reposition. The reposition dialog is for changing due dates only. If it's not working for you, then check the config options, make sure they are both set to true.

**Comment by omega3** [comment]
I set these values:

```
    "browser": {
        "replace_brower_reposition": true,
        "replace_brower_reschedule": true,
        "skip_new_card_types_on_reposition": false
    },
```

I created new test card and used reposition dilog:

I set start position to -14
step 14

and it changed due date but interval changed from new to 1.
screenshots
https://imgur.com/a/kAIoyJn

**Comment by lovac42** [comment]
1) No negative values. Positive values only.
-14 is not a valid input. Did you forget to read the wiki?
https://github.com/lovac42/ReMemorize/wiki/ReMemorize-User-Inputs

2) What is wrong here? You can not have an interval of 0 for review cards, that is invalid for review cards, so it was changed to the graduating interval.

Please spend more time reading the Anki manual and understand how these numbers are calculated and how it works.

Edit to add:
It seems you are trying to schedule new cards to be reviewed on a specific date as new cards with all the learning steps. That is impossible for Anki's default behavior, new cards can't have schedule information, and will not show up for review on schedule.
