### ISSUE TITLE
Error dialog: Invalid search

### ISSUE THREAD

**Issue by galantra** [lovac42/ReMemorize#16]
![grafik](https://user-images.githubusercontent.com/52420923/62762302-16f5bc80-ba89-11e9-9d03-d64a40576f26.png)
Just downloaded it and restarted anki. Am I doing something wrong?

**Comment by lovac42** [comment]
Sorry there was a typo in the instructions, its rate**d**:1:0 past tense with a d.
https://apps.ankiweb.net/docs/manual.html#searching
