### ISSUE TITLE
reposition from browser - minimum step

### ISSUE THREAD

**Issue by ijgnd** [lovac42/ReMemorize#18]
On reddit someone asked if there's a [Better way to review ahead?](https://www.reddit.com/r/Anki/comments/b63b48/better_way_to_review_ahead/). There was also this question:

> Also I think with the rememorize add-on you could solve this whole issue very easily by sorting for all cards due tomorrow with an interval greater than 15 (or whatever you wanted) and then using the rememorize add-on to change the due date from tomorrow to today. As far as I can tell, that would be a better solution than any of these. Am I thinking through anything incorrectly?

My reply was that this (only change the due date but not the interval) would work and that you can do this with ReMemorize from the browser by using "reposition". But as far as I see the minimum allowed value for the step QSpinBox is 1 (day) so only one card that you reposition would be due today so that you would have to run it many times. 

I tentatively suggested to add `frm.step.setMinimum(0)` into the function [reposition](https://github.com/lovac42/ReMemorize/blob/master/src/rememorize/main.py#L88). Is this a good addition?

**Comment by ijgnd** [comment]
sorry. it helps to really test all options and read the manual before posting.

**Comment by lovac42** [comment]
I plan to write my own gui for those instead of tabbing into Anki's reposition. So that should lessen the confusion. It was a poor decision due to time constraints at the time.
