### ISSUE TITLE
Why does the ease of changed cards change to 130%?

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/ReMemorize#2]
I noticed that the cards changed by its addon, has the facility changed to 130%. Because?

![image](https://user-images.githubusercontent.com/42243532/48300052-a3089280-e4bd-11e8-895f-df926c108fa0.png)

**Comment by cjdduarte** [comment]
I've analyzed your code and made this change. I noticed that the new cards got the initial value of 0 (zero) and after the first study, it changed to 130%.

This modification answered me. See if something should not be done about it.

![image](https://user-images.githubusercontent.com/42243532/48300419-33e26c80-e4c4-11e8-82f1-b447239b71e3.png)

**Comment by lovac42** [comment]
Do you have another addon causing this? Isolate the addons and test them again, this couldn't have been cause by my addon.

**Comment by cjdduarte** [comment]
I'll do a test and I'll come back.

**Comment by lovac42** [comment]
If you remove my addon, it's still set to 130. So this may be what happened. Anki initializes the new cards to 0, and sets it to 2500 after you first graded it. So if you reschedule a new card, it skips the initialization process and the next time it comes around, Anki see's 0 as invalid changes it to 1300 which is the smallest number allowed. In your picture, is the 0% and 250% the same card as the 130%? It shouldn't change the 250% to 130% at all.

**Comment by cjdduarte** [comment]
**The error occurs when I use a negative number.**

I tested in a new installation:

![image](https://user-images.githubusercontent.com/42243532/48306598-894d6680-e522-11e8-8bf1-a5ef39409dc5.png)


**I created a new card:**

![image](https://user-images.githubusercontent.com/42243532/48306614-ec3efd80-e522-11e8-9cc3-a327ac6b690c.png)

**In the first study, I used its addon and used the value "-1"**

![image](https://user-images.githubusercontent.com/42243532/48306625-227c7d00-e523-11e8-8462-02cd6864bbc3.png)

**Here are the new values:**

![image](https://user-images.githubusercontent.com/42243532/48306642-58b9fc80-e523-11e8-884c-297c631f5094.png)

**To test the "future", I'm using the "runasdate" application and disable the internet.**

![image](https://user-images.githubusercontent.com/42243532/48306666-b6e6df80-e523-11e8-9104-ac2ef4c47822.png)

**Now I will use the card and mark "Good", and it will reschedule for 2 days.**

![image](https://user-images.githubusercontent.com/42243532/48306691-23fa7500-e524-11e8-8db8-76c9475ccc7d.png)

![image](https://user-images.githubusercontent.com/42243532/48306700-64f28980-e524-11e8-8ca8-91c82094ea1e.png)

**The addon did everything correctly, however the ease was up to 130%.**

![image](https://user-images.githubusercontent.com/42243532/48306701-776cc300-e524-11e8-9275-581c7b9386c2.png)

Would not it be the case that your addon has placed 250% if the card is new (0%) and used the negative value?

**Comment by lovac42** [comment]
Yes, see my comments above yours. `In your picture, is the 0% and 250% the same card as the 130%? It shouldn't change the 250% to 130% at all.`

I will add some code to initialize the card. Here's the new changes. https://github.com/lovac42/ReMemorize/blob/initNewCards/src/rememorize/utils.py

**Comment by cjdduarte** [comment]
Thank you, I believe it will work. I will do the final test when you publish.

An observation. I use the default value (250%), but if another user uses a different value, I think the most correct place to get the information would be here:

![image](https://user-images.githubusercontent.com/42243532/48307275-9709e880-e530-11e8-9f07-4d2d05d432db.png)

But the way you did, you'll answer me.

**Comment by lovac42** [comment]
You can test them for me now by copying and overwriting your local copy. But I do believe this will solve the issue. Thanks for bringing it to my attention.

**Comment by cjdduarte** [comment]
It worked.

![image](https://user-images.githubusercontent.com/42243532/48307446-dede3f00-e533-11e8-9cbb-a347988eab4d.png)

**Comment by cjdduarte** [comment]
Sorry, I took the wrong test.

**Comment by cjdduarte** [comment]
I tested it with your new code and it did not work. I used the value "-40" and the card continued 0%

**Comment by lovac42** [comment]
yeah sorry forgot about negative values. This will do it. https://github.com/lovac42/ReMemorize/blob/initNewCards/src/rememorize/rememorize.py

**Comment by cjdduarte** [comment]
It's OK. Thank you.

**Comment by cjdduarte** [comment]
Tanks
