### ISSUE TITLE
Anki 2.1.24beta support

### ISSUE THREAD

**Issue by AnKingMed** [lovac42/ReMemorize#23]
On ankiweb this is marked as only working for anki 2.1.23.  As far as I can tell it seems to work fine on 2.1.24 beta. Is there any reason you marked it as non-compatible?

Edit: I guess I hadn't looked around enough.  Looks like the reschedule in browser doesn't work.

**Comment by AnKingMed** [comment]
Unless there was an update I didn't see, this seems to be working now on Anki 2.1.24beta 3 (it was not working on beta2)

**Comment by lovac42** [comment]
Beta1 and 2 had problems even without addons.

#22 
https://github.com/lovac42/ReMemorize/releases

**Comment by AnKingMed** [comment]
Cool.  Thanks for the fixes.  I'm doing what I can to test the betas and notify if I see anythign weird.  Love your addons!

**Comment by silentcicada1** [comment]
I am actually still having an issue with it. I keep getting the error stating it is not available for my version of anki (2.1.24beta 3)

**Comment by AnKingMed** [comment]
You have to go into .meta and change the -23 max version to 24 every day (because anki auto updates)

@lovac42 your current version seems to be working for me if you want to upload that on Ankiweb?

**Comment by lovac42** [comment]
A normal user shouldn't be using the anki beta. It will take weeks before he release this as stable and things might change, it always does.

**Comment by lovac42** [comment]
I just saw a large jump on RM's download count. So I'm guessing users are downgrading? That's enough reason to post this early than. But keep me informed if you guys run into errors.
