### ISSUE TITLE
Rescheduling, in Browse screen, after rating / reviewieing the card which was due Today

### ISSUE THREAD

**Issue by dedu6ka** [lovac42/ReMemorize#29]
These were my steps: 
1. Review cards due Today 
2. Overview the results, http://prntscr.com/vtvq7c 
3. Reschedule 3 cards ( as a group) which had somewhat low intervals. 
4. INFO screen shows that the 2nd rep from the top was NOT overwritten !

**Comment by lovac42** [comment]
Looks fine. It's not suppose to be overwritten. One was logged as "review" and the other was logged as "resched". This is also how anki 2.1.36 will work in the future.

**Comment by dedu6ka** [comment]
But I do not need to review the card in 7 days; will Anki skip 7d interval review ?

**Comment by lovac42** [comment]
I'm not sure what you are talking about.

Card was reviewed in the reviewer and graded as "Good" (3) on Dec 1st with a 7d next interval. It was then rescheduled 18 minutes later in the browser with a 20d interval. This card will be due in 20 days on Dec 21st 2020.

**Comment by dedu6ka** [comment]
What I am suggesting is to emulate the code for the Next-%; Anki compares two values ( the Minimum ivl and Next-% ivl) and discards the lower ivl. 
In my case, Anki should discard the 7d ivl. 

The similar situation exists in the Learning phase: Anki lets me skip one or all remaining Learning Steps and select the "Easy" button. 

Bottom line: i suggest skipping 7d ivl. 

Thanks for reading.

**Comment by lovac42** [comment]
You skip it by not grading your reviews. Use Ctrl+M and reschedule it in the reviewer for 20d.

The 7d was recorded by anki, not this addon. I would be taking a huge risk modifying the review logs. And the current approach is also used by future versions of anki 2.1.36.

**Comment by dedu6ka** [comment]
I am curios to see hoe the History table will look like ..  

Thank you for the comprehensive answer. 

PS. Your add-ons are amazing ! And i am so glad that you do not use the .gif files !
