### ISSUE TITLE
Suggestion: flag or mark

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/ReMemorize#3]
I would suggest that it be possible (by parameterization) that the cards modified by their addon, were marked by a mark or a flag.

So during a future review, I would know that that card had a modified schedule.

![image](https://user-images.githubusercontent.com/42243532/48300095-57a2b400-e4be-11e8-95fc-9ec8ac6f00d5.png)

**Comment by lovac42** [comment]
That is a nice idea, but should not part of this addon. Could easily be accomplished by using another addon to scan for reschedules changes.

**Comment by cjdduarte** [comment]
OK.
