### ISSUE TITLE
Batch processing - it's possible?

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/ReMemorize#5]
Would it be possible to put the options of this addon for a batch processing?
Example: I would like to reprogram 1, 10 or 1,000 cards at a time.
I could do it this way:

![example](https://user-images.githubusercontent.com/42243532/48979799-f4f90d00-f0a6-11e8-8683-12adf2075277.png)

**Comment by lovac42** [comment]
Just for ease factor? It would be alot easier and cleaner to just write another addon that does this rather than corrupt something that works into spaghetti code that would become hard to maintain.

**Comment by cjdduarte** [comment]
No. The idea was to use Rescheduler.
Ex: I would like to get all new cards and change them to review mode, 7 days.

Similar to this:
![image](https://user-images.githubusercontent.com/42243532/48986667-0a018a80-f0ff-11e8-8fc6-ad61a93424ec.png)

but in batch.

I'm trying to adapt your code, but using something like this, I'd like to use a tada function in this type of code:

```
    cids = self.selectedCards()
    for cid in cids:
```
**I do not see problem in being a new addon.**

**Comment by lovac42** [comment]
The browser already have features for reschedule.

But if you want to do it through Rememorize with logging, the current version supports runhooks. So you could just call:
```
        runHook('ReMemorize.forget', mycardA)
        runHook('ReMemorize.reschedule', mycardB, 5)
        runHook('ReMemorize.changeDue', mycardC, 10)
```

mycardA B C will be the current selected card in the browser.
5 and 10 will be the new due date.

If you use card id, then you would need to get the cards first one by one.
So somthing like:
```
card=mw.col.getCard(cid)
runHook('ReMemorize.reschedule', card, 5)
```

**Comment by cjdduarte** [comment]
Tanks.
